version: '3.6'
services:
 api:
   container_name: api
   build:
     context: ./
     dockerfile: Dockerfile
   volumes:
     - ./:/root/src
   healthcheck:
     disable: true
   restart: unless-stopped
   ports:
     - 3001:3001
   tty: true
 db:
   image: mongo:latest
   ports:
     - 27017:27017
   environment:
     MONGO_INITDB_ROOT_USERNAME: daniCabrera
     MONGO_INITDB_ROOT_PASSWORD: h9mh9mNto4uOGrTNipB
     MONGO_INITDB_DATABASE: test
